/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Tools.ConnectionManager;
import Tools.EncryptPassword;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class Authentification extends javax.swing.JFrame {
    
    /***************************************************************************
     * Les élèments de connection à la base de données *************************
     **************************************************************************/
    Connection connection = null;       
    ResultSet rs = null;                
    ResultSet rs2 = null;
    PreparedStatement ps = null;
    EncryptPassword encryptPwd;
    
    //------------ Cosnstructeur ----------
    public Authentification() throws SQLException, ClassNotFoundException {
        initComponents();
        this.errorLbl.setVisible(false);
        
        //--------- Se connecter à la BDD 
        connection = ConnectionManager.getConnection();
    
        
        //----- Centrer la fenetre 
        Dimension screenSize,frameSize;
        int x,y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize=getSize();
        x=(screenSize.width-frameSize.width)/2;
        y=(screenSize.height-frameSize.height)/2;
        setLocation(x, y);
        
        //------ mettre la fenetre non Resizable
        this.setResizable(false);
        
        //------ Icon de frame
        Image icon = Toolkit.getDefaultToolkit().getImage(Authentification.class.getResource("/images/o3.png"));  
        this.setIconImage(icon);   
        
        //------ Titre de frame
        this.setTitle("Authentification");
    }

    
    //------------ Cosnstructeur ----------
    public Authentification(String email, String password) throws SQLException, ClassNotFoundException {
        initComponents();
        this.emailTxt.setText(email);
        this.passwordTxt.setText(password);
        this.errorLbl.setVisible(false);
        
        //--------- Se connecter à la BDD 
        connection = ConnectionManager.getConnection();
    
        
        //----- Centrer la fenetre 
        Dimension screenSize,frameSize;
        int x,y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize=getSize();
        x=(screenSize.width-frameSize.width)/2;
        y=(screenSize.height-frameSize.height)/2;
        setLocation(x, y);
        
        //------ mettre la fenetre non Resizable
        this.setResizable(false);
        
        //------ Icon de frame
        Image icon = Toolkit.getDefaultToolkit().getImage(Authentification.class.getResource("/images/o3.png"));  
        this.setIconImage(icon);   
        
        //------ Titre de frame
        this.setTitle("Authentification");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        emailLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        connexionBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        inscrireBtn = new javax.swing.JButton();
        emailTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");

        contentPanel.setBackground(new java.awt.Color(243, 241, 199));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLbl.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        emailLbl.setText("E-mail :");
        contentPanel.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 102, 41));

        passwordLbl.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        passwordLbl.setText("Mot de passe :");
        contentPanel.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 42));

        titleLbl.setFont(new java.awt.Font("Charlemagne Std", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 255));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Authentification");
        contentPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 700, 79));

        passwordTxt.setBackground(new java.awt.Color(250, 249, 241));
        passwordTxt.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        passwordTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contentPanel.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 245, 42));

        connexionBtn.setBackground(new java.awt.Color(0, 0, 255));
        connexionBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        connexionBtn.setForeground(new java.awt.Color(255, 255, 255));
        connexionBtn.setText("Se connecter");
        connexionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionBtnActionPerformed(evt);
            }
        });
        contentPanel.add(connexionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 41));

        errorLbl.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLbl.setText("E-mail ou mot de passe incorrect !");
        contentPanel.add(errorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 258, 254, 47));

        inscrireBtn.setBackground(new java.awt.Color(0, 0, 255));
        inscrireBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        inscrireBtn.setForeground(new java.awt.Color(255, 255, 255));
        inscrireBtn.setText("S'inscrire");
        inscrireBtn.setActionCommand("");
        inscrireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireBtnActionPerformed(evt);
            }
        });
        contentPanel.add(inscrireBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 117, 41));

        emailTxt.setBackground(new java.awt.Color(250, 249, 241));
        emailTxt.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        contentPanel.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 245, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a1_opt.png"))); // NOI18N
        contentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 108, 213, -1));

        exit.setBackground(new java.awt.Color(225, 7, 14));
        exit.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Quitter");
        exit.setToolTipText("");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        contentPanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1_opt.png"))); // NOI18N
        contentPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //------------ Button d'inscription ----------
    private void inscrireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireBtnActionPerformed
 
        try {
            Inscription in = new Inscription();
            in.setVisible(true);
        this.dispose();
        } catch (SQLException ex) {
            
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inscrireBtnActionPerformed

    
    //------------ Button d'Authentification ----------
    private void connexionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionBtnActionPerformed
        
        int idUser = 0;
        String emailUser = this.emailTxt.getText();
        String passwordUser = this.passwordTxt.getText();
                
        try {
            try {
                encryptPwd = new EncryptPassword();
            } catch (Exception ex) {
                Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            /*******************************************************************
             * On selectionne a partir de la BDD l'id du joueur si tous les 
             * informations entrées par le joueur sont correcte
             ******************************************************************/
            ps = connection.prepareStatement("Select idUser from user where emailUser=? and passwordUser=?");
            ps.setString(1, emailUser);
            ps.setString(2, encryptPwd.encrypt(passwordUser));
            rs = ps.executeQuery(); 
            
            
            while(this.rs.next()) {
                
                //------ retourner l'id de l'tilisateur
                idUser = this.rs.getInt(1);
                
                //------ fermer la page d'authentification
                dispose(); 
                errorLbl.setVisible(false);

                Home.idUser = idUser;
                Home home = new Home();
                home.setVisible(true);

                break;
            }
            errorLbl.setVisible(true);
                        
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_connexionBtnActionPerformed

    //------------ Button de quitter ----------
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose(); 
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Authentification().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connexionBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JButton exit;
    private javax.swing.JButton inscrireBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
