/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;

public class BoardPanel extends javax.swing.JPanel {
    
    public static Cellule board [];          //------ Tables des cellule qui vont construire notre othellier
    public static int TAILLE_BOARD = 400;    //------ Dimension de notre plateau   
    
   
    //------- Constructeur -----------
    public BoardPanel() {
        initComponents();
        creation();
    }
    
    //----------- Getter--------------
    public Cellule[] getBoard()
    {
        return board;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //------ Creation des cellules -----------
    public void creation() {
        
        //------ L'instanciation 
        board = new Cellule[64];     
        
        int count = 0;
        int k = 0;
        
        /***********************************************************************
         * Nous avons creé une tables des celllules, chaque ligne de "board" va
         * contenir 8 cellules et de meme, chaque colonne va contenir 8 cases,
         * pour ceci, on a besoin de deux boucles pour dessiner 8 cellules sur 
         * la meme ligne, puis revenir a la ligne et dessines 8 cellules aussi, 
         * et ainsi de suite
         **********************************************************************/
        for(int i = 0; i < 8; i++)
        {
            for(int j = 0; j < 8; j++)
            {
                count++;
                if(count % 9 == 0)
                    break;
                board[k] = new Cellule(k);
                board[k].setBounds(j * Cellule.TAILLE_CELL, i * Cellule.TAILLE_CELL, Cellule.TAILLE_CELL, Cellule.TAILLE_CELL);
                board[k].addMouseListener(board[k]);
                this.add(board[k]);
                k++;
            }
            count = 0;
        }
        
        //------- dessiner les 4 pions de debut
        board[27].drawPion(Color.white);
        board[28].drawPion(Color.black);
        board[35].drawPion(Color.black);
        board[36].drawPion(Color.white);
        
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
